/**
 * Static fallback registry used when GitHub API is unreachable (e.g. local builds
 * without internet). This file is auto-generated — run `npm run sync-docs` to
 * refresh it from the live API.
 *
 * In production CI, the GitHub API is used directly and this file is ignored.
 */

import type { RepoDocsConfig } from "@/lib/github";

const OWNER = process.env.NEXT_PUBLIC_GITHUB_OWNER ?? "";

function f(name: string, files: string[]): { name: string; files: { path: string; title: string; size: number }[] } {
  return {
    name,
    files: files.map((p) => ({
      path: p,
      title: p
        .split("/")
        .pop()!
        .replace(/\.md$/, "")
        .replace(/^\d+-/, "")
        .replace(/[-_]/g, " ")
        .replace(/\b\w/g, (c) => c.toUpperCase()),
      size: 5000,
    })),
  };
}

export const FALLBACK_REGISTRY: RepoDocsConfig[] = (
  [
    {
      repo: "DotnetKafka",
      name: "Kafka Deep Dive",
      description: "Producers, consumers, KRaft, streaming, schema registry, and production operations",
      language: "C#",
      branch: "main",
      topics: [],
      htmlUrl: "https://github.com/${OWNER}/DotnetKafka",
      updatedAt: "",
      stars: 0,
      languageStats: {},
      totalFiles: 0,
      totalSize: 0,
      docs: [
        f("docs", [
          "docs/README.md",
          "docs/02-kraft-mode.md",
          "docs/04-consumers-deep-dive.md",
          "docs/08-streaming-and-realtime.md",
          "docs/09-use-cases-and-patterns.md",
          "docs/10-production-operations.md",
          "docs/14-schema-registry.md",
          "docs/16-testing-strategies.md",
          "docs/18-topic-design-cookbook.md",
          "docs/19-troubleshooting-runbook.md",
          "docs/20-glossary.md",
        ]),
      ],
    },
    {
      repo: "Daprtutorial",
      name: "Dapr Tutorial",
      description: "Complete guide to Dapr — service invocation, state management, pub/sub, actors, workflows",
      language: "C#",
      branch: "main",
      topics: [],
      htmlUrl: "https://github.com/${OWNER}/Daprtutorial",
      updatedAt: "",
      stars: 0,
      languageStats: {},
      totalFiles: 0,
      totalSize: 0,
      docs: [
        f("docs", [
          "docs/01-dapr-architecture.md",
          "docs/02-service-invocation.md",
          "docs/03-state-management.md",
          "docs/04-pubsub.md",
          "docs/05-bindings.md",
          "docs/07-actors.md",
          "docs/08-workflows.md",
          "docs/11-security.md",
          "docs/13-dapr-on-kubernetes.md",
          "docs/14-production-readiness.md",
        ]),
      ],
    },
    {
      repo: "DotnetOidc",
      name: "OIDC & OAuth2",
      description: "OpenID Connect flows, token validation, middleware, Keycloak integration",
      language: "C#",
      branch: "main",
      topics: [],
      htmlUrl: "https://github.com/${OWNER}/DotnetOidc",
      updatedAt: "",
      stars: 0,
      languageStats: {},
      totalFiles: 0,
      totalSize: 0,
      docs: [
        f("docs", [
          "docs/01-architecture-overview.md",
          "docs/02-oidc-flows.md",
          "docs/03-configuration.md",
          "docs/05-token-validation.md",
          "docs/06-middleware-and-pipeline.md",
          "docs/08-api-reference.md",
          "docs/10-security.md",
          "docs/12-keycloak-integration.md",
        ]),
      ],
    },
    {
      repo: "DotnetDomainDrivenDesign",
      name: "Domain-Driven Design",
      description: "Strategic design, aggregates, event sourcing, projections, Kafka/Redis integration",
      language: "C#",
      branch: "main",
      topics: [],
      htmlUrl: "https://github.com/${OWNER}/DotnetDomainDrivenDesign",
      updatedAt: "",
      stars: 0,
      languageStats: {},
      totalFiles: 0,
      totalSize: 0,
      docs: [
        f("docs", [
          "docs/strategic-design.md",
          "docs/aggregates-and-invariants.md",
          "docs/event-sourcing-overview.md",
          "docs/projections-and-read-models.md",
          "docs/kafka-integration.md",
          "docs/redis-usage.md",
          "docs/migration-from-crud-to-ddd.md",
        ]),
      ],
    },
    {
      repo: "DotnetAdvanceDesignPattern",
      name: "Advanced Design Patterns",
      description: "Enterprise patterns, decision matrices, pattern selection guide, and interview cheatsheets",
      language: "C#",
      branch: "main",
      topics: [],
      htmlUrl: "https://github.com/${OWNER}/DotnetAdvanceDesignPattern",
      updatedAt: "",
      stars: 0,
      languageStats: {},
      totalFiles: 0,
      totalSize: 0,
      docs: [
        f("docs", [
          "docs/design-pattern-categories.md",
          "docs/comparison-maps.md",
          "docs/decision-matrix.md",
          "docs/enterprise-patterns-summary.md",
          "docs/pattern-selection-guide.md",
          "docs/interview-revision-cheatsheet.md",
        ]),
      ],
    },
    {
      repo: "DotnetRegularExpression",
      name: "Regex Mastery",
      description: "Regex engine internals, lookahead/lookbehind, performance pitfalls",
      language: "C#",
      branch: "main",
      topics: [],
      htmlUrl: "https://github.com/${OWNER}/DotnetRegularExpression",
      updatedAt: "",
      stars: 0,
      languageStats: {},
      totalFiles: 0,
      totalSize: 0,
      docs: [
        f("docs", [
          "docs/00-index.md",
          "docs/01-regex-engine-internals.md",
          "docs/05-lookahead-lookbehind.md",
          "docs/08-performance-and-pitfalls.md",
          "docs/09-method-selection-guide.md",
          "docs/10-visual-cheat-sheet.md",
        ]),
      ],
    },
    {
      repo: "AkkaDotnetTutorial",
      name: "Akka.NET",
      description: "Actor model architecture, persistence, event sourcing, pub/sub, streams",
      language: "C#",
      branch: "main",
      topics: [],
      htmlUrl: "https://github.com/${OWNER}/AkkaDotnetTutorial",
      updatedAt: "",
      stars: 0,
      languageStats: {},
      totalFiles: 0,
      totalSize: 0,
      docs: [
        f("docs", ["docs/00-architecture-overview.md", "docs/03-persistence-event-sourcing.md", "docs/04-pubsub-kafka-redis.md", "docs/05-streams-pipeline.md", "docs/06-coordination-sharding.md"]),
      ],
    },
    {
      repo: "DotnetCQRS",
      name: "CQRS Pattern",
      description: "CQRS fundamentals, validation pipelines, architecture deep dive",
      language: "C#",
      branch: "main",
      topics: [],
      htmlUrl: "https://github.com/${OWNER}/DotnetCQRS",
      updatedAt: "",
      stars: 0,
      languageStats: {},
      totalFiles: 0,
      totalSize: 0,
      docs: [f("docs", ["docs/cqrs-fundamentals.md", "docs/architecture.md", "docs/validation-and-pipelines.md", "docs/running-the-project.md"])],
    },
    {
      repo: "DotnetServerSentEvent",
      name: "Server-Sent Events",
      description: "SSE architecture, scaling strategies, and SignalR vs SSE vs WebSocket comparison",
      language: "C#",
      branch: "main",
      topics: [],
      htmlUrl: "https://github.com/${OWNER}/DotnetServerSentEvent",
      updatedAt: "",
      stars: 0,
      languageStats: {},
      totalFiles: 0,
      totalSize: 0,
      docs: [f("docs", ["docs/SSE-Architecture-and-Core-Concepts.md", "docs/Scaling-Strategies.md", "docs/SignalR-vs-SSE-vs-WebSocket-Comparison.md"])],
    },
    {
      repo: "DotnetRabbitMQ",
      name: "RabbitMQ",
      description: "RabbitMQ concepts, retry patterns, and dead-letter queues",
      language: "C#",
      branch: "main",
      topics: [],
      htmlUrl: "https://github.com/${OWNER}/DotnetRabbitMQ",
      updatedAt: "",
      stars: 0,
      languageStats: {},
      totalFiles: 0,
      totalSize: 0,
      docs: [f("docs", ["docs/rabbitmq-concepts.md", "docs/retry-dlq.md"])],
    },
    {
      repo: "Certificate-mtls",
      name: "mTLS & Certificates",
      description: "Mutual TLS device-to-service authentication and Dapr mTLS architecture",
      language: "Python",
      branch: "main",
      topics: [],
      htmlUrl: "https://github.com/${OWNER}/Certificate-mtls",
      updatedAt: "",
      stars: 0,
      languageStats: {},
      totalFiles: 0,
      totalSize: 0,
      docs: [f("docs", ["docs/03-mtls-device-to-service.md", "docs/04-dapr-mtls-architecture.md"])],
    },
    {
      repo: "CypressTutorial",
      name: "Cypress Testing",
      description: "CI/CD strategy, debugging, flake reduction, page objects, and reliable E2E patterns",
      language: "TypeScript",
      branch: "main",
      topics: [],
      htmlUrl: "https://github.com/${OWNER}/CypressTutorial",
      updatedAt: "",
      stars: 0,
      languageStats: {},
      totalFiles: 0,
      totalSize: 0,
      docs: [f("docs", ["docs/ci-cd-strategy.md", "docs/debugging-guide.md", "docs/flake-reduction.md", "docs/page-object-vs-app-actions.md", "docs/reliable-e2e-patterns.md"])],
    },
    {
      repo: "DotnetGraphQL",
      name: "GraphQL",
      description: "GraphQL architecture with .NET — schema design, resolvers, best practices",
      language: "C#",
      branch: "main",
      topics: [],
      htmlUrl: "https://github.com/${OWNER}/DotnetGraphQL",
      updatedAt: "",
      stars: 0,
      languageStats: {},
      totalFiles: 0,
      totalSize: 0,
      docs: [f("docs", ["docs/architecture.md"])],
    },
    {
      repo: "DotnetKeda",
      name: "KEDA Autoscaling",
      description: "KEDA fundamentals, Grafana observability, k6 testing, and Kubernetes deployment",
      language: "C#",
      branch: "main",
      topics: [],
      htmlUrl: "https://github.com/${OWNER}/DotnetKeda",
      updatedAt: "",
      stars: 0,
      languageStats: {},
      totalFiles: 0,
      totalSize: 0,
      docs: [f("docs", ["docs/keda-fundamentals.md", "docs/grafana-observability.md", "docs/k6-testing.md", "docs/running-on-kubernetes.md"])],
    },
    {
      repo: "DotnetNginx",
      name: "Nginx & K3s",
      description: "DNS resolution, Helmfile deployment, K3s setup, and Dapr integration",
      language: "Shell",
      branch: "main",
      topics: [],
      htmlUrl: "https://github.com/${OWNER}/DotnetNginx",
      updatedAt: "",
      stars: 0,
      languageStats: {},
      totalFiles: 0,
      totalSize: 0,
      docs: [f("docs", ["docs/dapr-deep-dive.md", "docs/dns-resolution-flow.md", "docs/helmfile-deployment.md", "docs/k3s-setup.md"])],
    },
    {
      repo: "DotnetPbacAbacRbac",
      name: "Authorization Patterns",
      description: "PBAC, ABAC, RBAC, OAuth2 flows, and OIDC overview",
      language: "C#",
      branch: "main",
      topics: [],
      htmlUrl: "https://github.com/${OWNER}/DotnetPbacAbacRbac",
      updatedAt: "",
      stars: 0,
      languageStats: {},
      totalFiles: 0,
      totalSize: 0,
      docs: [f("docs", ["docs/oidc-and-oauth2-overview.md", "docs/authorization-code-flow.md", "docs/client-credentials-flow.md", "docs/abac.md", "docs/running-the-project.md"])],
    },
    {
      repo: "Dotnetty",
      name: "Dotnetty Protocol",
      description: "Custom protocol implementation and architecture with Dotnetty",
      language: "C#",
      branch: "main",
      topics: [],
      htmlUrl: "https://github.com/${OWNER}/Dotnetty",
      updatedAt: "",
      stars: 0,
      languageStats: {},
      totalFiles: 0,
      totalSize: 0,
      docs: [f("docs", ["docs/ARCHITECTURE.md", "docs/PROTOCOL.md"])],
    },
    {
      repo: "LinuxProgramming",
      name: "Linux Programming",
      description: "Linux fundamentals, command cheatsheets, and networking reference",
      language: "Shell",
      branch: "main",
      topics: [],
      htmlUrl: "https://github.com/${OWNER}/LinuxProgramming",
      updatedAt: "",
      stars: 0,
      languageStats: {},
      totalFiles: 0,
      totalSize: 0,
      docs: [f("docs", ["docs/01-linux-fundamentals.md"]), f("docs/cheatsheets", ["docs/cheatsheets/linux-commands.md", "docs/cheatsheets/networking.md"])],
    },
    {
      repo: "DistributedLog",
      name: "Distributed Logging",
      description: "Structured logging, log correlation, ELK vs Datadog, and Datadog architecture",
      language: "C#",
      branch: "main",
      topics: [],
      htmlUrl: "https://github.com/${OWNER}/DistributedLog",
      updatedAt: "",
      stars: 0,
      languageStats: {},
      totalFiles: 0,
      totalSize: 0,
      docs: [f("docs", ["docs/structured-logging-strategy.md", "docs/log-correlation-strategy.md", "docs/elk-vs-datadog.md", "docs/datadog-architecture.md", "docs/legacy-log-transformation.md"])],
    },
    {
      repo: "DistributedSystemWithBigData",
      name: "Distributed Systems",
      description: "Replication strategies, partitioning, and tenant sharding",
      language: "C#",
      branch: "main",
      topics: [],
      htmlUrl: "https://github.com/${OWNER}/DistributedSystemWithBigData",
      updatedAt: "",
      stars: 0,
      languageStats: {},
      totalFiles: 0,
      totalSize: 0,
      docs: [f("docs/replication", ["docs/replication/leader-follower.md", "docs/replication/leaderless.md"]), f("docs/partitioning", ["docs/partitioning/tenant-sharding.md"])],
    },
    {
      repo: "Angular21",
      name: "Angular 21",
      description: "Signal store patterns, testing strategy, and project setup for modern Angular",
      language: "TypeScript",
      branch: "main",
      topics: [],
      htmlUrl: "https://github.com/${OWNER}/Angular21",
      updatedAt: "",
      stars: 0,
      languageStats: {},
      totalFiles: 0,
      totalSize: 0,
      docs: [f("docs", ["docs/running-the-project.md", "docs/signal-store-patterns.md", "docs/testing-strategy.md"])],
    },
    {
      repo: "SystemDesign",
      name: "System Design",
      description: "High-level design breakdowns for system design interviews",
      language: "C#",
      branch: "main",
      topics: [],
      htmlUrl: "https://github.com/${OWNER}/SystemDesign",
      updatedAt: "",
      stars: 0,
      languageStats: {},
      totalFiles: 0,
      totalSize: 0,
      docs: [f("docs/hld", ["docs/hld/18-slack-part1.md"])],
    },
  ] as RepoDocsConfig[]
).map((r) => ({ ...r, htmlUrl: `https://github.com/${OWNER}/${r.repo}` }));
